//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5448
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.5448.
// 
#pragma warning disable 1591

namespace Portal_GEFACE.RoleService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RoleServiceSoap", Namespace="http://CDI/Services/")]
    public partial class RoleService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddUsersToRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApplicationNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetApplicationNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindUsersInRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRolesForUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersInRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUserInRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveUsersFromRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RoleExistsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RoleService() {
            this.Url = global::Portal_GEFACE.Properties.Settings.Default.Portal_GEFACE_RoleService_RoleService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddUsersToRolesCompletedEventHandler AddUsersToRolesCompleted;
        
        /// <remarks/>
        public event GetApplicationNameCompletedEventHandler GetApplicationNameCompleted;
        
        /// <remarks/>
        public event SetApplicationNameCompletedEventHandler SetApplicationNameCompleted;
        
        /// <remarks/>
        public event CreateRoleCompletedEventHandler CreateRoleCompleted;
        
        /// <remarks/>
        public event DeleteRoleCompletedEventHandler DeleteRoleCompleted;
        
        /// <remarks/>
        public event FindUsersInRoleCompletedEventHandler FindUsersInRoleCompleted;
        
        /// <remarks/>
        public event GetAllRolesCompletedEventHandler GetAllRolesCompleted;
        
        /// <remarks/>
        public event GetRolesForUserCompletedEventHandler GetRolesForUserCompleted;
        
        /// <remarks/>
        public event GetUsersInRoleCompletedEventHandler GetUsersInRoleCompleted;
        
        /// <remarks/>
        public event IsUserInRoleCompletedEventHandler IsUserInRoleCompleted;
        
        /// <remarks/>
        public event RemoveUsersFromRolesCompletedEventHandler RemoveUsersFromRolesCompleted;
        
        /// <remarks/>
        public event RoleExistsCompletedEventHandler RoleExistsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/AddUsersToRoles", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddUsersToRoles(string sServiceKey, string[] usernames, string[] roleNames) {
            object[] results = this.Invoke("AddUsersToRoles", new object[] {
                        sServiceKey,
                        usernames,
                        roleNames});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddUsersToRolesAsync(string sServiceKey, string[] usernames, string[] roleNames) {
            this.AddUsersToRolesAsync(sServiceKey, usernames, roleNames, null);
        }
        
        /// <remarks/>
        public void AddUsersToRolesAsync(string sServiceKey, string[] usernames, string[] roleNames, object userState) {
            if ((this.AddUsersToRolesOperationCompleted == null)) {
                this.AddUsersToRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUsersToRolesOperationCompleted);
            }
            this.InvokeAsync("AddUsersToRoles", new object[] {
                        sServiceKey,
                        usernames,
                        roleNames}, this.AddUsersToRolesOperationCompleted, userState);
        }
        
        private void OnAddUsersToRolesOperationCompleted(object arg) {
            if ((this.AddUsersToRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUsersToRolesCompleted(this, new AddUsersToRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/GetApplicationName", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetApplicationName() {
            object[] results = this.Invoke("GetApplicationName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetApplicationNameAsync() {
            this.GetApplicationNameAsync(null);
        }
        
        /// <remarks/>
        public void GetApplicationNameAsync(object userState) {
            if ((this.GetApplicationNameOperationCompleted == null)) {
                this.GetApplicationNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApplicationNameOperationCompleted);
            }
            this.InvokeAsync("GetApplicationName", new object[0], this.GetApplicationNameOperationCompleted, userState);
        }
        
        private void OnGetApplicationNameOperationCompleted(object arg) {
            if ((this.GetApplicationNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApplicationNameCompleted(this, new GetApplicationNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/SetApplicationName", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetApplicationName(string name) {
            object[] results = this.Invoke("SetApplicationName", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetApplicationNameAsync(string name) {
            this.SetApplicationNameAsync(name, null);
        }
        
        /// <remarks/>
        public void SetApplicationNameAsync(string name, object userState) {
            if ((this.SetApplicationNameOperationCompleted == null)) {
                this.SetApplicationNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetApplicationNameOperationCompleted);
            }
            this.InvokeAsync("SetApplicationName", new object[] {
                        name}, this.SetApplicationNameOperationCompleted, userState);
        }
        
        private void OnSetApplicationNameOperationCompleted(object arg) {
            if ((this.SetApplicationNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetApplicationNameCompleted(this, new SetApplicationNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/CreateRole", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateRole(string sServiceKey, string roleName) {
            object[] results = this.Invoke("CreateRole", new object[] {
                        sServiceKey,
                        roleName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateRoleAsync(string sServiceKey, string roleName) {
            this.CreateRoleAsync(sServiceKey, roleName, null);
        }
        
        /// <remarks/>
        public void CreateRoleAsync(string sServiceKey, string roleName, object userState) {
            if ((this.CreateRoleOperationCompleted == null)) {
                this.CreateRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRoleOperationCompleted);
            }
            this.InvokeAsync("CreateRole", new object[] {
                        sServiceKey,
                        roleName}, this.CreateRoleOperationCompleted, userState);
        }
        
        private void OnCreateRoleOperationCompleted(object arg) {
            if ((this.CreateRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRoleCompleted(this, new CreateRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/DeleteRole", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteRole(string sServiceKey, string roleName, bool throwOnPopulatedRole) {
            object[] results = this.Invoke("DeleteRole", new object[] {
                        sServiceKey,
                        roleName,
                        throwOnPopulatedRole});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRoleAsync(string sServiceKey, string roleName, bool throwOnPopulatedRole) {
            this.DeleteRoleAsync(sServiceKey, roleName, throwOnPopulatedRole, null);
        }
        
        /// <remarks/>
        public void DeleteRoleAsync(string sServiceKey, string roleName, bool throwOnPopulatedRole, object userState) {
            if ((this.DeleteRoleOperationCompleted == null)) {
                this.DeleteRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRoleOperationCompleted);
            }
            this.InvokeAsync("DeleteRole", new object[] {
                        sServiceKey,
                        roleName,
                        throwOnPopulatedRole}, this.DeleteRoleOperationCompleted, userState);
        }
        
        private void OnDeleteRoleOperationCompleted(object arg) {
            if ((this.DeleteRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRoleCompleted(this, new DeleteRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/FindUsersInRole", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FindUsersInRole(string sServiceKey, string roleName, string usernameToMatch) {
            object[] results = this.Invoke("FindUsersInRole", new object[] {
                        sServiceKey,
                        roleName,
                        usernameToMatch});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FindUsersInRoleAsync(string sServiceKey, string roleName, string usernameToMatch) {
            this.FindUsersInRoleAsync(sServiceKey, roleName, usernameToMatch, null);
        }
        
        /// <remarks/>
        public void FindUsersInRoleAsync(string sServiceKey, string roleName, string usernameToMatch, object userState) {
            if ((this.FindUsersInRoleOperationCompleted == null)) {
                this.FindUsersInRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindUsersInRoleOperationCompleted);
            }
            this.InvokeAsync("FindUsersInRole", new object[] {
                        sServiceKey,
                        roleName,
                        usernameToMatch}, this.FindUsersInRoleOperationCompleted, userState);
        }
        
        private void OnFindUsersInRoleOperationCompleted(object arg) {
            if ((this.FindUsersInRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindUsersInRoleCompleted(this, new FindUsersInRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/GetAllRoles", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllRoles(string sServiceKey) {
            object[] results = this.Invoke("GetAllRoles", new object[] {
                        sServiceKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllRolesAsync(string sServiceKey) {
            this.GetAllRolesAsync(sServiceKey, null);
        }
        
        /// <remarks/>
        public void GetAllRolesAsync(string sServiceKey, object userState) {
            if ((this.GetAllRolesOperationCompleted == null)) {
                this.GetAllRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRolesOperationCompleted);
            }
            this.InvokeAsync("GetAllRoles", new object[] {
                        sServiceKey}, this.GetAllRolesOperationCompleted, userState);
        }
        
        private void OnGetAllRolesOperationCompleted(object arg) {
            if ((this.GetAllRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRolesCompleted(this, new GetAllRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/GetRolesForUser", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetRolesForUser(string username) {
            object[] results = this.Invoke("GetRolesForUser", new object[] {
                        username});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRolesForUserAsync(string username) {
            this.GetRolesForUserAsync(username, null);
        }
        
        /// <remarks/>
        public void GetRolesForUserAsync(string username, object userState) {
            if ((this.GetRolesForUserOperationCompleted == null)) {
                this.GetRolesForUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRolesForUserOperationCompleted);
            }
            this.InvokeAsync("GetRolesForUser", new object[] {
                        username}, this.GetRolesForUserOperationCompleted, userState);
        }
        
        private void OnGetRolesForUserOperationCompleted(object arg) {
            if ((this.GetRolesForUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRolesForUserCompleted(this, new GetRolesForUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/GetUsersInRole", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUsersInRole(string sServiceKey, string roleName) {
            object[] results = this.Invoke("GetUsersInRole", new object[] {
                        sServiceKey,
                        roleName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersInRoleAsync(string sServiceKey, string roleName) {
            this.GetUsersInRoleAsync(sServiceKey, roleName, null);
        }
        
        /// <remarks/>
        public void GetUsersInRoleAsync(string sServiceKey, string roleName, object userState) {
            if ((this.GetUsersInRoleOperationCompleted == null)) {
                this.GetUsersInRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersInRoleOperationCompleted);
            }
            this.InvokeAsync("GetUsersInRole", new object[] {
                        sServiceKey,
                        roleName}, this.GetUsersInRoleOperationCompleted, userState);
        }
        
        private void OnGetUsersInRoleOperationCompleted(object arg) {
            if ((this.GetUsersInRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersInRoleCompleted(this, new GetUsersInRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/IsUserInRole", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsUserInRole(string username, string roleName) {
            object[] results = this.Invoke("IsUserInRole", new object[] {
                        username,
                        roleName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUserInRoleAsync(string username, string roleName) {
            this.IsUserInRoleAsync(username, roleName, null);
        }
        
        /// <remarks/>
        public void IsUserInRoleAsync(string username, string roleName, object userState) {
            if ((this.IsUserInRoleOperationCompleted == null)) {
                this.IsUserInRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUserInRoleOperationCompleted);
            }
            this.InvokeAsync("IsUserInRole", new object[] {
                        username,
                        roleName}, this.IsUserInRoleOperationCompleted, userState);
        }
        
        private void OnIsUserInRoleOperationCompleted(object arg) {
            if ((this.IsUserInRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUserInRoleCompleted(this, new IsUserInRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/RemoveUsersFromRoles", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveUsersFromRoles(string sServiceKey, string[] usernames, string[] roleNames) {
            object[] results = this.Invoke("RemoveUsersFromRoles", new object[] {
                        sServiceKey,
                        usernames,
                        roleNames});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveUsersFromRolesAsync(string sServiceKey, string[] usernames, string[] roleNames) {
            this.RemoveUsersFromRolesAsync(sServiceKey, usernames, roleNames, null);
        }
        
        /// <remarks/>
        public void RemoveUsersFromRolesAsync(string sServiceKey, string[] usernames, string[] roleNames, object userState) {
            if ((this.RemoveUsersFromRolesOperationCompleted == null)) {
                this.RemoveUsersFromRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveUsersFromRolesOperationCompleted);
            }
            this.InvokeAsync("RemoveUsersFromRoles", new object[] {
                        sServiceKey,
                        usernames,
                        roleNames}, this.RemoveUsersFromRolesOperationCompleted, userState);
        }
        
        private void OnRemoveUsersFromRolesOperationCompleted(object arg) {
            if ((this.RemoveUsersFromRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveUsersFromRolesCompleted(this, new RemoveUsersFromRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CDI/Services/RoleExists", RequestNamespace="http://CDI/Services/", ResponseNamespace="http://CDI/Services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RoleExists(string sServiceKey, string roleName) {
            object[] results = this.Invoke("RoleExists", new object[] {
                        sServiceKey,
                        roleName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RoleExistsAsync(string sServiceKey, string roleName) {
            this.RoleExistsAsync(sServiceKey, roleName, null);
        }
        
        /// <remarks/>
        public void RoleExistsAsync(string sServiceKey, string roleName, object userState) {
            if ((this.RoleExistsOperationCompleted == null)) {
                this.RoleExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRoleExistsOperationCompleted);
            }
            this.InvokeAsync("RoleExists", new object[] {
                        sServiceKey,
                        roleName}, this.RoleExistsOperationCompleted, userState);
        }
        
        private void OnRoleExistsOperationCompleted(object arg) {
            if ((this.RoleExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RoleExistsCompleted(this, new RoleExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AddUsersToRolesCompletedEventHandler(object sender, AddUsersToRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUsersToRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUsersToRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetApplicationNameCompletedEventHandler(object sender, GetApplicationNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApplicationNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApplicationNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SetApplicationNameCompletedEventHandler(object sender, SetApplicationNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetApplicationNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetApplicationNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void CreateRoleCompletedEventHandler(object sender, CreateRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void DeleteRoleCompletedEventHandler(object sender, DeleteRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void FindUsersInRoleCompletedEventHandler(object sender, FindUsersInRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindUsersInRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindUsersInRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetAllRolesCompletedEventHandler(object sender, GetAllRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetRolesForUserCompletedEventHandler(object sender, GetRolesForUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRolesForUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRolesForUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetUsersInRoleCompletedEventHandler(object sender, GetUsersInRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersInRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersInRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void IsUserInRoleCompletedEventHandler(object sender, IsUserInRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUserInRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUserInRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RemoveUsersFromRolesCompletedEventHandler(object sender, RemoveUsersFromRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveUsersFromRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveUsersFromRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void RoleExistsCompletedEventHandler(object sender, RoleExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoleExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RoleExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591